#!/usr/bin/env bash
# Create an SSH key pair with a passphrase
# Requirements: name of the created private key must be school
#               passphrase must be betty
#               key size must be 4096 bits

PRIVATE_KEY="school"
PASSPHRASE="betty"
BITS=4096

ssh-keygen -t rsa -b $BITS -f $PRIVATE_KEY -N "$PASSPHRASE" -C "ubuntu@school"
