#!/usr/bin/env bash
# Create an SSH key pair with a passphrase
# Requirements: name of the created private key must be school
#               passphrase must be betty
#               key size must be 4096 bits

ssh-keygen -t rsa -b 4096 -f school -N "betty"
