#!/usr/bin/env bash
# tranfers a file to the server
# Check if all 4 parameters are passed
if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

echo "FILE_PATH=$1"
echo "SERVER_IP=$2"
echo "USERNAME=$3"
echo "SSH_KEY=$4"

# Transfer the file using scp
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVERIP:~/"
