#!/usr/bin/env bash
# this script redirects 
set -e

sudo apt-get -y update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html

sudo tee /etc/nginx/sites-available/default > /dev/null << 'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
	
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOF

sudo service nginx restart
sudo service nginx reload
