#!/usr/bin/env bash
# configures nginx with a custom 404 page

set -e

sudo apt-get update -y
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo tee /etc/nginx/sites-available/default > /dev/null << 'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	server_name _;

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
